package com.lizhendong.web.dao;

import com.lizhendong.web.entity.Test;
import org.apache.ibatis.annotations.Insert;

public interface TestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbggenerated
     */
    @Insert({
        "insert into test (test1, test2)",
        "values (#{test1,jdbcType=VARCHAR}, #{test2,jdbcType=VARCHAR})"
    })
    int insert(Test record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbggenerated
     */
    int insertSelective(Test record);
}