package com.lizhendong.web.entity;

public class Test {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.test1
     *
     * @mbggenerated
     */
    private String test1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.test2
     *
     * @mbggenerated
     */
    private String test2;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbggenerated
     */
    public Test(String test1, String test2) {
        this.test1 = test1;
        this.test2 = test2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.test1
     *
     * @return the value of test.test1
     *
     * @mbggenerated
     */
    public String getTest1() {
        return test1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.test2
     *
     * @return the value of test.test2
     *
     * @mbggenerated
     */
    public String getTest2() {
        return test2;
    }
}